name: Build Ghostscript & gs_pclm.so for ARM64

on:
  workflow_dispatch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ "aarch64-linux-gnu" ]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config libpng-dev zlib1g-dev \
            libnode-dev \
            gcc-${{ matrix.toolchain }} \
            g++-${{ matrix.toolchain }} \
            wget cmake ninja-build

      - name: Download Ghostscript
        run: |
          wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs9561/ghostscript-9.56.1.tar.gz
          tar xzf ghostscript-9.56.1.tar.gz

      - name: Build Ghostscript
        run: |
          cd ghostscript-9.56.1
          ./configure \
            --host=${{ matrix.toolchain }} \
            --disable-shared --enable-static \
            --disable-gtk --without-x \
            --prefix=$PWD/install
          make -j$(nproc) && make install

      - name: Upload Ghostscript binary
        uses: actions/upload-artifact@v4
        with:
          name: gs-arm64
          path: ghostscript-9.56.1/install/bin/gs

      - name: Build NAPI module
        run: |
          cmake -S entry/src/main/cpp -B native-build \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=${{ matrix.toolchain }}-gcc \
            -DCMAKE_CXX_COMPILER=${{ matrix.toolchain }}-g++ \
            -DCMAKE_BUILD_TYPE=Release \
            -GNinja
          cmake --build native-build -- -j$(nproc)

      - name: Check exported symbols
        run: |
          echo "Looking for napi_register_module_v1…"
          nm -g native-build/libgs_pclm.z.so | grep napi_register_module_v1

      - name: Upload NAPI module
        uses: actions/upload-artifact@v4
        with:
          name: gs_pclm-so-arm64
          path: native-build/libgs_pclm.z.so
