name: Build Ghostscript ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GS_VER: 9.56.1
  GS_TAG: gs9561

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cross-compile toolchain and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libpng-dev \
            zlib1g-dev \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            wget

      - name: Download Ghostscript source
        run: |
          wget https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/${{ env.GS_TAG }}/ghostscript-${{ env.GS_VER }}.tar.gz
          tar xzf ghostscript-${{ env.GS_VER }}.tar.gz

      - name: Configure and Build for ARM64
        run: |
          cd ghostscript-${{ env.GS_VER }}
          ./configure \
            --host=aarch64-linux-gnu \
            --disable-shared \
            --enable-static \
            --disable-gtk --without-x \
            --prefix=$PWD/install
          make -j$(nproc)
          make install

      - name: Upload ARM64 gs binary
        uses: actions/upload-artifact@v4
        with:
          name: gs-arm64
          path: ghostscript-${{ env.GS_VER }}/install/bin/gs
