jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ "aarch64-linux-gnu" ]
    steps:
      - uses: actions/checkout@v4

      - name: Install cross‐compile deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libpng-dev \
            zlib1g-dev \
            gcc-${{ matrix.toolchain }} \
            g++-${{ matrix.toolchain }} \
            wget \
            cmake \
            ninja-build

      # …后面下载 Ghostscript、cmake native 模块等步骤不变
